import type { ModelRegistryEntry } from "./schemas.js";

const OPENAI_MODEL_DOCS = "https://developers.openai.com/api/docs/models";
const OPENAI_GPT55_LAUNCH = "https://openai.com/index/introducing-gpt-5-5/";
const OPENAI_PRICING = "https://developers.openai.com/api/docs/pricing";
const ANTHROPIC_MODELS = "https://platform.claude.com/docs/en/about-claude/models/overview";
const ANTHROPIC_OPUS_47 = "https://www.anthropic.com/news/claude-opus-4-7";
const ANTHROPIC_PRICING = "https://claude.com/pricing";
const GOOGLE_MODELS = "https://ai.google.dev/gemini-api/docs/models";
const GOOGLE_PRICING = "https://ai.google.dev/gemini-api/docs/pricing";
const GOOGLE_GEMINI_31_PRO_CARD = "https://deepmind.google/models/model-cards/gemini-3-1-pro/";
const GOOGLE_GEMINI_31_PRO_LAUNCH =
  "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-1-pro/";
const GOOGLE_GEMINI_31_FLASH_LITE_LAUNCH =
  "https://blog.google/innovation-and-ai/models-and-research/gemini-models/gemini-3-1-flash-lite/";

export const DEFAULT_MODEL_REGISTRY: ModelRegistryEntry[] = [
  {
    id: "claude-opus-4-7",
    provider: "anthropic",
    access_mode: "claude_code",
    status: "stable",
    tier: "frontier",
    release_date: "2026-04-16",
    task_fit: {
      planning: 0.98,
      architecture: 0.98,
      coding_heavy: 0.99,
      review: 0.98,
      refactor: 0.97,
      tiny_edit: 0.45,
      long_context: 0.94,
    },
    context_window: 1_000_000,
    input_price_usd_per_mtok: 5,
    output_price_usd_per_mtok: 25,
    strengths: [
      "frontier coding and AI-agent work",
      "long-horizon planning",
      "complex code review",
      "instruction following on hard tasks",
    ],
    weaknesses: ["expensive for simple edits", "consumer quota pressure", "restricted cyber behavior by policy"],
    latency_class: "medium",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Claude Code authentication through the official CLI.",
    routing_tags: ["planner_master", "agentic_coding", "architecture", "review", "long_context"],
    benchmark_scores: [
      {
        name: "CursorBench",
        score: "70%",
        source: "Anthropic Opus 4.7 launch",
        notes: "Reported as a jump from 58% on Opus 4.6.",
      },
      {
        name: "BigLaw Bench",
        score: "90.9%",
        mode: "high effort",
        source: "Anthropic Opus 4.7 launch",
      },
      {
        name: "Internal 93-task coding benchmark",
        score: "+13% vs Opus 4.6",
        source: "Anthropic Opus 4.7 launch",
      },
      {
        name: "Visual-acuity benchmark",
        score: "98.5%",
        source: "Anthropic Opus 4.7 launch",
        notes: "XBOW computer-use visual benchmark.",
      },
    ],
    recommended_uses: [
      "default Claude planner when quota is available",
      "hard architecture decomposition",
      "multi-step implementation handoffs",
      "critical review tasks",
    ],
    avoid_for: ["bulk formatting", "simple JSON rewrites", "quota-constrained sessions"],
    source_urls: [ANTHROPIC_MODELS, ANTHROPIC_OPUS_47, ANTHROPIC_PRICING],
  },
  {
    id: "claude-sonnet-4-6",
    provider: "anthropic",
    access_mode: "claude_code",
    status: "stable",
    tier: "balanced",
    task_fit: {
      planning: 0.91,
      architecture: 0.9,
      coding_heavy: 0.92,
      review: 0.91,
      refactor: 0.9,
      tiny_edit: 0.65,
      long_context: 0.9,
    },
    context_window: 1_000_000,
    input_price_usd_per_mtok: 3,
    output_price_usd_per_mtok: 15,
    strengths: ["balanced speed and intelligence", "everyday coding", "analysis", "content tasks"],
    weaknesses: ["less capable than Opus 4.7 on the hardest long-running coding tasks"],
    latency_class: "low",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Claude Code authentication through the official CLI.",
    routing_tags: ["balanced_worker", "coding", "review", "analysis"],
    benchmark_scores: [],
    recommended_uses: ["default Claude worker for routine coding", "review tasks where Opus would be overkill"],
    avoid_for: ["highest-risk architecture decisions when Opus quota is available"],
    source_urls: [ANTHROPIC_MODELS, ANTHROPIC_PRICING],
  },
  {
    id: "claude-haiku-4-5",
    provider: "anthropic",
    access_mode: "claude_code",
    status: "stable",
    tier: "utility",
    task_fit: {
      planning: 0.72,
      architecture: 0.68,
      coding_heavy: 0.72,
      review: 0.72,
      refactor: 0.74,
      tiny_edit: 0.92,
      long_context: 0.62,
    },
    context_window: 200_000,
    input_price_usd_per_mtok: 1,
    output_price_usd_per_mtok: 5,
    strengths: ["fastest Claude tier", "near-frontier intelligence for small work", "low-cost utility tasks"],
    weaknesses: ["not the right choice for high-risk planning or complex architecture"],
    latency_class: "low",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Claude Code authentication through the official CLI.",
    routing_tags: ["fast_worker", "tiny_edit", "classification", "structured_output"],
    benchmark_scores: [],
    recommended_uses: ["small fixes", "classification", "summaries", "structured transformations"],
    avoid_for: ["core planner role", "large refactors", "high-risk reviews"],
    source_urls: [ANTHROPIC_MODELS, ANTHROPIC_PRICING],
  },
  {
    id: "gpt-5.5",
    provider: "openai",
    access_mode: "codex_cli",
    status: "stable",
    tier: "frontier",
    release_date: "2026-04-23",
    task_fit: {
      planning: 0.99,
      architecture: 0.98,
      coding_heavy: 0.98,
      review: 0.96,
      refactor: 0.97,
      tiny_edit: 0.62,
      long_context: 0.96,
    },
    context_window: 1_000_000,
    max_output_tokens: 128_000,
    input_price_usd_per_mtok: 5,
    output_price_usd_per_mtok: 30,
    strengths: [
      "complex reasoning and coding",
      "tool-heavy agents",
      "long-context retrieval",
      "product-spec-to-plan workflows",
    ],
    weaknesses: ["overkill for simple edits", "consumer plan and Codex availability can vary by account"],
    latency_class: "medium",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Codex authentication through the official CLI.",
    routing_tags: ["planner_master", "agentic_coding", "long_context", "tool_use", "knowledge_work"],
    benchmark_scores: [
      {
        name: "Terminal-Bench 2.0",
        score: "82.7%",
        source: "OpenAI GPT-5.5 launch",
      },
      {
        name: "SWE-Bench Pro",
        score: "58.6%",
        source: "OpenAI GPT-5.5 launch",
      },
      {
        name: "GDPval",
        score: "84.9%",
        mode: "wins or ties",
        source: "OpenAI GPT-5.5 launch",
      },
      {
        name: "OSWorld-Verified",
        score: "78.7%",
        source: "OpenAI GPT-5.5 launch",
      },
      {
        name: "BrowseComp",
        score: "84.4%",
        source: "OpenAI GPT-5.5 launch",
      },
      {
        name: "ARC-AGI-2",
        score: "85.0%",
        mode: "Verified",
        source: "OpenAI GPT-5.5 launch",
      },
    ],
    recommended_uses: [
      "default OpenAI planner",
      "complex coding",
      "agentic terminal workflows",
      "large-system refactors",
      "document-grounded planning",
    ],
    avoid_for: ["tiny deterministic edits", "tasks where OpenAI is not in the active model pool"],
    source_urls: [OPENAI_MODEL_DOCS, OPENAI_GPT55_LAUNCH, OPENAI_PRICING],
  },
  {
    id: "gpt-5.5-pro",
    provider: "openai",
    access_mode: "chatgpt_codex",
    status: "restricted",
    tier: "frontier",
    release_date: "2026-04-23",
    task_fit: {
      planning: 0.99,
      architecture: 0.99,
      coding_heavy: 0.96,
      review: 0.98,
      refactor: 0.94,
      tiny_edit: 0.4,
      long_context: 0.94,
    },
    input_price_usd_per_mtok: 15,
    output_price_usd_per_mtok: 90,
    strengths: ["highest-accuracy OpenAI reasoning mode", "business/legal/data-science polish", "hardest reviews"],
    weaknesses: ["expensive", "not always exposed through the same non-interactive CLI path"],
    latency_class: "high",
    cost_class: "subscription",
    privacy_notes: "Availability depends on the user's ChatGPT/Codex plan and OpenAI rollout state.",
    routing_tags: ["highest_accuracy", "planning", "review", "knowledge_work"],
    benchmark_scores: [
      {
        name: "BrowseComp",
        score: "90.1%",
        source: "OpenAI GPT-5.5 launch",
      },
      {
        name: "Humanity's Last Exam",
        score: "57.2%",
        mode: "with tools",
        source: "OpenAI GPT-5.5 launch",
      },
    ],
    recommended_uses: ["rare highest-confidence planning passes", "final review of very high-risk plans"],
    avoid_for: ["default worker routing", "latency-sensitive tasks", "accounts without Pro-level availability"],
    source_urls: [OPENAI_MODEL_DOCS, OPENAI_GPT55_LAUNCH, OPENAI_PRICING],
  },
  {
    id: "gpt-5.4",
    provider: "openai",
    access_mode: "codex_cli",
    status: "stable",
    tier: "balanced",
    task_fit: {
      planning: 0.9,
      architecture: 0.9,
      coding_heavy: 0.92,
      review: 0.9,
      refactor: 0.92,
      tiny_edit: 0.72,
      long_context: 0.9,
    },
    context_window: 1_000_000,
    max_output_tokens: 128_000,
    input_price_usd_per_mtok: 2.5,
    output_price_usd_per_mtok: 15,
    strengths: ["affordable professional coding", "tool use", "long context", "computer use"],
    weaknesses: ["below GPT-5.5 on complex agentic work"],
    latency_class: "low",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Codex authentication through the official CLI.",
    routing_tags: ["balanced_worker", "coding", "refactor", "tool_use"],
    benchmark_scores: [
      {
        name: "Terminal-Bench 2.0",
        score: "75.1%",
        source: "OpenAI GPT-5.5 launch",
      },
      {
        name: "GDPval",
        score: "83.0%",
        mode: "wins or ties",
        source: "OpenAI GPT-5.5 launch",
      },
    ],
    recommended_uses: ["routine OpenAI coding workers", "refactors", "cost-aware planning"],
    avoid_for: ["hardest planning tasks when GPT-5.5 is available"],
    source_urls: [OPENAI_MODEL_DOCS, OPENAI_GPT55_LAUNCH, OPENAI_PRICING],
  },
  {
    id: "gpt-5.4-mini",
    provider: "openai",
    access_mode: "codex_cli",
    status: "stable",
    tier: "utility",
    task_fit: {
      planning: 0.68,
      architecture: 0.66,
      coding_heavy: 0.7,
      review: 0.72,
      refactor: 0.78,
      tiny_edit: 0.94,
      long_context: 0.74,
    },
    context_window: 400_000,
    max_output_tokens: 128_000,
    input_price_usd_per_mtok: 0.75,
    output_price_usd_per_mtok: 4.5,
    strengths: ["low latency", "low cost", "coding subagents", "simple transformations"],
    weaknesses: ["not suited for high-risk planning or deep architecture decisions"],
    latency_class: "low",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Codex authentication through the official CLI.",
    routing_tags: ["fast_worker", "tiny_edit", "structured_output", "subagent"],
    benchmark_scores: [],
    recommended_uses: ["small edits", "JSON/YAML transformations", "test fixture updates", "mechanical refactors"],
    avoid_for: ["planner master", "large ambiguous implementation tasks"],
    source_urls: [OPENAI_MODEL_DOCS, OPENAI_PRICING],
  },
  {
    id: "gemini-3.1-pro-preview",
    provider: "google",
    access_mode: "gemini_cli",
    status: "preview",
    tier: "frontier",
    release_date: "2026-02-19",
    task_fit: {
      planning: 0.96,
      architecture: 0.95,
      coding_heavy: 0.93,
      review: 0.92,
      refactor: 0.92,
      tiny_edit: 0.72,
      long_context: 0.99,
    },
    context_window: 1_048_576,
    max_output_tokens: 65_536,
    input_price_usd_per_mtok: 2,
    output_price_usd_per_mtok: 12,
    strengths: [
      "multimodal long context",
      "advanced reasoning",
      "agentic workflows",
      "vibe-coding and interactive UI prototypes",
    ],
    weaknesses: ["preview model can change", "higher price for prompts over 200k tokens"],
    latency_class: "medium",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Gemini CLI authentication through the official CLI.",
    routing_tags: ["planner_master", "long_context", "multimodal", "reasoning", "frontend"],
    benchmark_scores: [
      {
        name: "SWE-Bench Verified",
        score: "80.6%",
        mode: "single attempt",
        source: "Gemini 3.1 Pro model card",
      },
      {
        name: "SWE-Bench Pro",
        score: "54.2%",
        mode: "single attempt",
        source: "Gemini 3.1 Pro model card",
      },
      {
        name: "LiveCodeBench Pro",
        score: "2887 Elo",
        source: "Gemini 3.1 Pro model card",
      },
      {
        name: "ARC-AGI-2",
        score: "77.1%",
        mode: "ARC Prize Verified",
        source: "Gemini 3.1 Pro model card",
      },
      {
        name: "BrowseComp",
        score: "85.9%",
        source: "Gemini 3.1 Pro model card",
      },
      {
        name: "MRCR v2 8-needle",
        score: "84.9% at 128k average; 26.3% at 1M pointwise",
        source: "Gemini 3.1 Pro model card",
      },
    ],
    recommended_uses: [
      "default Google planner",
      "large-context analysis",
      "multimodal planning",
      "frontend-heavy prototypes",
      "research synthesis",
    ],
    avoid_for: ["ultra-cheap high-volume utility tasks", "users who require stable non-preview model behavior"],
    source_urls: [GOOGLE_MODELS, GOOGLE_GEMINI_31_PRO_CARD, GOOGLE_GEMINI_31_PRO_LAUNCH, GOOGLE_PRICING],
  },
  {
    id: "gemini-3.1-pro-preview-customtools",
    provider: "google",
    access_mode: "gemini_cli",
    status: "preview",
    tier: "specialized",
    release_date: "2026-02-19",
    task_fit: {
      planning: 0.94,
      architecture: 0.94,
      coding_heavy: 0.96,
      review: 0.92,
      refactor: 0.94,
      tiny_edit: 0.7,
      long_context: 0.98,
    },
    context_window: 1_048_576,
    max_output_tokens: 65_536,
    input_price_usd_per_mtok: 2,
    output_price_usd_per_mtok: 12,
    strengths: ["custom tool prioritization", "bash-heavy agentic workflows", "long context", "code execution"],
    weaknesses: ["preview quality can fluctuate outside custom-tool workflows"],
    latency_class: "medium",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Gemini CLI authentication through the official CLI.",
    routing_tags: ["agentic_coding", "custom_tools", "bash", "long_context"],
    benchmark_scores: [
      {
        name: "Inherited Gemini 3.1 Pro capability profile",
        score: "see gemini-3.1-pro-preview",
        source: "Gemini API model docs",
      },
    ],
    recommended_uses: ["workers that rely on bash/custom tools", "repo-editing agents with many custom tool calls"],
    avoid_for: ["plain chat planning without custom tools", "stable-production model requirements"],
    source_urls: [GOOGLE_MODELS, GOOGLE_GEMINI_31_PRO_CARD, GOOGLE_PRICING],
  },
  {
    id: "gemini-3-flash-preview",
    provider: "google",
    access_mode: "gemini_cli",
    status: "preview",
    tier: "balanced",
    release_date: "2025-12-01",
    task_fit: {
      planning: 0.84,
      architecture: 0.82,
      coding_heavy: 0.86,
      review: 0.84,
      refactor: 0.88,
      tiny_edit: 0.9,
      long_context: 0.88,
    },
    context_window: 1_048_576,
    max_output_tokens: 65_536,
    input_price_usd_per_mtok: 0.5,
    output_price_usd_per_mtok: 3,
    strengths: ["frontier-class speed/cost balance", "computer use support", "grounding", "structured outputs"],
    weaknesses: ["less capable than Gemini 3.1 Pro for the hardest planning tasks"],
    latency_class: "low",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Gemini CLI authentication through the official CLI.",
    routing_tags: ["fast_worker", "coding", "computer_use", "grounding", "structured_output"],
    benchmark_scores: [],
    recommended_uses: ["cost-aware coding workers", "grounded utility tasks", "computer-use workflows"],
    avoid_for: ["highest-risk master planning when Gemini 3.1 Pro is available"],
    source_urls: [GOOGLE_MODELS, GOOGLE_PRICING],
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    provider: "google",
    access_mode: "gemini_cli",
    status: "preview",
    tier: "utility",
    release_date: "2026-03-03",
    task_fit: {
      planning: 0.62,
      architecture: 0.6,
      coding_heavy: 0.66,
      review: 0.68,
      refactor: 0.76,
      tiny_edit: 0.96,
      long_context: 0.82,
    },
    context_window: 1_048_576,
    max_output_tokens: 65_536,
    input_price_usd_per_mtok: 0.25,
    output_price_usd_per_mtok: 1.5,
    strengths: ["cheapest Gemini 3.1 text model", "fast high-volume tasks", "translation", "simple data extraction"],
    weaknesses: ["not for complex architecture or hard debugging"],
    latency_class: "low",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Gemini CLI authentication through the official CLI.",
    routing_tags: ["cheap_worker", "tiny_edit", "translation", "classification", "data_extraction"],
    benchmark_scores: [
      {
        name: "Time to first answer token",
        score: "2.5x faster than 2.5 Flash",
        source: "Gemini 3.1 Flash-Lite launch",
      },
      {
        name: "Output speed",
        score: "+45% vs 2.5 Flash",
        source: "Gemini 3.1 Flash-Lite launch",
      },
    ],
    recommended_uses: ["bulk tiny edits", "translation", "classification", "low-risk extraction", "large batches"],
    avoid_for: ["planner master", "hard coding tasks", "security-sensitive review"],
    source_urls: [GOOGLE_MODELS, GOOGLE_GEMINI_31_FLASH_LITE_LAUNCH, GOOGLE_PRICING],
  },
];
