import type { ModelRegistryEntry } from "./schemas.js";

export const DEFAULT_MODEL_REGISTRY: ModelRegistryEntry[] = [
  {
    id: "claude-code-default",
    provider: "anthropic",
    access_mode: "claude_code",
    task_fit: {
      planning: 0.98,
      architecture: 0.96,
      coding_heavy: 0.94,
      review: 0.92,
      refactor: 0.9,
      tiny_edit: 0.55,
    },
    context_window: 200000,
    strengths: ["long-horizon planning", "complex coding", "review quality"],
    weaknesses: ["subscription quota pressure", "overkill for tiny deterministic edits"],
    latency_class: "medium",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Claude Code authentication through the official CLI.",
    recommended_uses: ["planner master", "architecture decomposition", "complex workers"],
    avoid_for: ["bulk formatting", "simple JSON rewrites"],
  },
  {
    id: "openai-codex-default",
    provider: "openai",
    access_mode: "codex_cli",
    task_fit: {
      planning: 0.9,
      architecture: 0.88,
      coding_heavy: 0.94,
      review: 0.9,
      refactor: 0.9,
      tiny_edit: 0.7,
    },
    strengths: ["coding agent workflows", "non-interactive execution", "structured outputs"],
    weaknesses: ["exact model availability depends on the user's Codex plan"],
    latency_class: "medium",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Codex authentication through the official CLI.",
    recommended_uses: ["coding workers", "review workers", "future supervisor mode"],
    avoid_for: ["tasks where the user did not enable OpenAI in the provider pool"],
  },
  {
    id: "gemini-cli-default",
    provider: "google",
    access_mode: "gemini_cli",
    task_fit: {
      planning: 0.82,
      architecture: 0.8,
      coding_heavy: 0.84,
      review: 0.82,
      refactor: 0.82,
      tiny_edit: 0.85,
      long_context: 0.92,
    },
    strengths: ["large context", "fast utility tasks", "Google account based auth"],
    weaknesses: ["quota and model tier depend on the user's Google account"],
    latency_class: "low",
    cost_class: "subscription",
    privacy_notes: "Uses the user's Gemini CLI authentication through the official CLI.",
    recommended_uses: ["long-context analysis", "JSON/regex/data transformation", "secondary workers"],
    avoid_for: ["tasks where Gemini CLI is unauthenticated or quota constrained"],
  },
];

